add option for undecorated AWT window
korlibs/korge pull request #1726
Opened 2023-06-26 03:55 UTC by cmhulbert

2023-06-26 11:16 UTC, soywiz commented
Nice. Thanks!

@cmhulbert 
What would you think about creating a `WindowConfig` class like 
`data class WindowConfig(val undecorated: Boolean, val transparent: Boolean, val allowMaximize, val allowMinimize..., val allowFullscreen: Boolean)` and then passing it instead of the undecorated to the korge method?

2023-06-28 13:55 UTC, soywiz requested changes

2023-06-28 13:55 UTC, soywiz commented on korge/src/commonMain/kotlin/korlibs/korge/Korge.kt
> +    undecorated: Boolean? = null,
Can you create a class called `WindowConfig`, initially with `data class WindowConfig(val undecorated: Boolean = false)`, so we can add there other stuff without polluting there method more.

Full proposal in the comment.

2023-06-28 18:26 UTC, cmhulbert commented
Yes! Sorry, haven't looked at this again yet, but I think that's a good idea. I hope to have some time to push some more changes tonight.

2023-07-02 03:01 UTC, cmhulbert commented
So, I put something similar to the changes you suggested. I'm open to suggestions for improvements. A couple things I noticed while doing this:
- There already is a `GameWindowCreationConfig` data class. should we just add to this, instead of a new `WindowConfig`?
- There is also a `GameWindow.configure` method which accepts `title`, `size`, `icon`, and `bgColor` as well. Should those all be put in the `WindowConfig` options?
- should `title` be in the `WindowConfig`?
- you suggested `transparent`. Is that separate from the window background color being specified as `Colors.TRANSPARENT`?

2023-07-03 07:46 UTC, soywiz commented
> So, I put something similar to the changes you suggested. I'm open to suggestions for improvements. A couple things I noticed while doing this:
> 
> * There already is a `GameWindowCreationConfig` data class. should we just add to this, instead of a new `WindowConfig`?

Yes, just checked, and this is in the common source set, so we should be able to use it when creating KorGE:
https://github.com/korlibs/korge/blob/d530d16e95471f2c0e9b17e0b3f116b7c0fb8e3b/korgw/src/commonMain/kotlin/korlibs/render/GameWindow.kt#L32-L40
I guess we should unify it there.

> * There is also a `GameWindow.configure` method which accepts `title`, `size`, `icon`, and `bgColor` as well. Should those all be put in the `WindowConfig` options?

Probably yes.

> * should `title` be in the `WindowConfig`?

Maybe yes too. But keeping the old properties as `@Deprecated`. Since it is a data class, maybe we can do something like:

```kotlin
data class Widow...Config...(val title: String = "...Game...")
fun Korge(
  title: String? = null,
  config: Window...Config...,
)... {
  // ...
  val config = config.copy(title = title ?: config.title, ...)
  // ...
}
```

So we can use the deprecated methods, but omiting them use the new WindowConfig way.

> * you suggested `transparent`. Is that separate from the window background color being specified as `Colors.TRANSPARENT`?

I would say yes. Though we can detect `Colors.TRANSPARENT` if it is provided in the `GameWindowConfig`

2023-11-03 11:17 UTC, closed without merging

2023-11-03 11:17 UTC, soywiz commented
I have backported it